name: expense_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Dependency injection
  get_it: ^8.0.0

  # Routes
  go_router: ^14.3.0

  # Provider
  provider: ^6.1.2
  path_provider: ^2.1.2

  # Intl
  intl: ^0.20.1

  # Widget
  flutter_slidable: ^3.0.1

  # BarGraph
  fl_chart: ^0.69.0

  # Fonts
  google_fonts: ^6.2.1

  # Spash - Icon
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.1

  # Preferences
  shared_preferences: ^2.2.2

  # Icons
  icons_plus: ^5.0.0

  # Drawer hidden
  flutter_advanced_drawer: ^1.3.6

  # Multiple Floating Action Buttons
  flutter_speed_dial: ^7.0.0

  # ObjectBox
  objectbox: ^4.0.2
  objectbox_flutter_libs: any

  # Input formatter
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  objectbox_generator: any

flutter:
  uses-material-design: true

  assets:
    - assets/
    - shorebird.yaml

# Splash
flutter_native_splash:
  color: "#000000"
  android: true
  ios: true
  image: assets/splash.png
  android_12:
    color: "#000000"
    image: assets/splash.png

#Icon
flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  min_sdk_android: 28
  image_path: "assets/icon_android.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon_android.png"
# dart run flutter_native_splash:create - Gerar splash screen
# dart run flutter_launcher_icons - Gerar ícone
